[build]
  command = "npm run build"
  publish = "dist/public"
  base = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200