[build]
  command = "npm run build"
  publish = "client/dist"
  base = "."
  
[functions]
  directory = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200